[2022-11-08T20:43:06.586+0000] {processor.py:154} INFO - Started process (PID=2009) to work on /opt/airflow/dags/6.2-monitoring.py
[2022-11-08T20:43:06.596+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/6.2-monitoring.py for tasks to queue
[2022-11-08T20:43:06.605+0000] {logging_mixin.py:120} INFO - [2022-11-08T20:43:06.604+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/6.2-monitoring.py
[2022-11-08T20:43:07.092+0000] {logging_mixin.py:120} INFO - [2022-11-08T20:43:07.035+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/6.2-monitoring.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/6.2-monitoring.py", line 27, in <module>
    depends_on_past=True
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 408, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 147, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 408, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 757, in __init__
    f"Invalid arguments were passed to {self.__class__.__name__} (task_id: {task_id}). "
airflow.exceptions.AirflowException: Invalid arguments were passed to BashOperator (task_id: task1). Invalid arguments were:
**kwargs: {'TriggerRule': <TriggerRule.ALL_SUCCESS: 'all_success'>}
[2022-11-08T20:43:07.097+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/6.2-monitoring.py
[2022-11-08T20:43:07.248+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/6.2-monitoring.py took 0.677 seconds
[2022-11-08T20:43:23.710+0000] {processor.py:154} INFO - Started process (PID=2028) to work on /opt/airflow/dags/6.2-monitoring.py
[2022-11-08T20:43:23.711+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/6.2-monitoring.py for tasks to queue
[2022-11-08T20:43:23.712+0000] {logging_mixin.py:120} INFO - [2022-11-08T20:43:23.712+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/6.2-monitoring.py
[2022-11-08T20:43:23.771+0000] {logging_mixin.py:120} INFO - [2022-11-08T20:43:23.756+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/6.2-monitoring.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/6.2-monitoring.py", line 27, in <module>
    depends_on_past=False
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 408, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 147, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 408, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 757, in __init__
    f"Invalid arguments were passed to {self.__class__.__name__} (task_id: {task_id}). "
airflow.exceptions.AirflowException: Invalid arguments were passed to BashOperator (task_id: task1). Invalid arguments were:
**kwargs: {'TriggerRule': <TriggerRule.ALL_SUCCESS: 'all_success'>}
[2022-11-08T20:43:23.772+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/6.2-monitoring.py
[2022-11-08T20:43:23.798+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/6.2-monitoring.py took 0.090 seconds
[2022-11-08T20:43:54.577+0000] {processor.py:154} INFO - Started process (PID=2065) to work on /opt/airflow/dags/6.2-monitoring.py
[2022-11-08T20:43:54.578+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/6.2-monitoring.py for tasks to queue
[2022-11-08T20:43:54.579+0000] {logging_mixin.py:120} INFO - [2022-11-08T20:43:54.578+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/6.2-monitoring.py
[2022-11-08T20:43:54.609+0000] {logging_mixin.py:120} INFO - [2022-11-08T20:43:54.601+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/6.2-monitoring.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/6.2-monitoring.py", line 27, in <module>
    depends_on_past=False
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 408, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 147, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 408, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 757, in __init__
    f"Invalid arguments were passed to {self.__class__.__name__} (task_id: {task_id}). "
airflow.exceptions.AirflowException: Invalid arguments were passed to BashOperator (task_id: task1). Invalid arguments were:
**kwargs: {'TriggerRule': <TriggerRule.ALL_SUCCESS: 'all_success'>}
[2022-11-08T20:43:54.609+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/6.2-monitoring.py
[2022-11-08T20:43:54.629+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/6.2-monitoring.py took 0.057 seconds
[2022-11-08T20:45:56.957+0000] {processor.py:154} INFO - Started process (PID=2106) to work on /opt/airflow/dags/6.2-monitoring.py
[2022-11-08T20:50:54.131+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/6.2-monitoring.py for tasks to queue
[2022-11-08T20:52:14.176+0000] {logging_mixin.py:120} INFO - [2022-11-08T20:52:14.174+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/6.2-monitoring.py
[2022-11-08T20:52:16.807+0000] {logging_mixin.py:120} INFO - [2022-11-08T20:52:16.720+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/6.2-monitoring.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/6.2-monitoring.py", line 27, in <module>
    depends_on_past=False
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 408, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 147, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 408, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 757, in __init__
    f"Invalid arguments were passed to {self.__class__.__name__} (task_id: {task_id}). "
airflow.exceptions.AirflowException: Invalid arguments were passed to BashOperator (task_id: task1). Invalid arguments were:
**kwargs: {'TriggerRule': <TriggerRule.ALL_SUCCESS: 'all_success'>}
[2022-11-08T20:52:16.824+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/6.2-monitoring.py
[2022-11-08T20:52:19.865+0000] {processor.py:154} INFO - Started process (PID=2115) to work on /opt/airflow/dags/6.2-monitoring.py
[2022-11-08T20:52:19.868+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/6.2-monitoring.py for tasks to queue
[2022-11-08T20:52:19.869+0000] {logging_mixin.py:120} INFO - [2022-11-08T20:52:19.869+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/6.2-monitoring.py
[2022-11-08T20:52:20.016+0000] {logging_mixin.py:120} INFO - [2022-11-08T20:52:19.999+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/6.2-monitoring.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/6.2-monitoring.py", line 27, in <module>
    depends_on_past=False
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 408, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 147, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 408, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 757, in __init__
    f"Invalid arguments were passed to {self.__class__.__name__} (task_id: {task_id}). "
airflow.exceptions.AirflowException: Invalid arguments were passed to BashOperator (task_id: task1). Invalid arguments were:
**kwargs: {'TriggerRule': <TriggerRule.ALL_SUCCESS: 'all_success'>}
[2022-11-08T20:52:20.018+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/6.2-monitoring.py
[2022-11-08T20:52:20.073+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/6.2-monitoring.py took 0.219 seconds
[2022-11-08T20:55:30.636+0000] {processor.py:154} INFO - Started process (PID=2137) to work on /opt/airflow/dags/6.2-monitoring.py
[2022-11-08T20:55:30.637+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/6.2-monitoring.py for tasks to queue
[2022-11-08T20:55:30.638+0000] {logging_mixin.py:120} INFO - [2022-11-08T20:55:30.638+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/6.2-monitoring.py
[2022-11-08T20:55:30.804+0000] {logging_mixin.py:120} INFO - [2022-11-08T20:55:30.754+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/6.2-monitoring.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/6.2-monitoring.py", line 27, in <module>
    depends_on_past=False
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 408, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 147, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 408, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 757, in __init__
    f"Invalid arguments were passed to {self.__class__.__name__} (task_id: {task_id}). "
airflow.exceptions.AirflowException: Invalid arguments were passed to BashOperator (task_id: task1). Invalid arguments were:
**kwargs: {'TriggerRule': <TriggerRule.ALL_SUCCESS: 'all_success'>}
[2022-11-08T20:55:30.805+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/6.2-monitoring.py
[2022-11-08T20:55:31.626+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/6.2-monitoring.py took 0.993 seconds
[2022-11-08T20:55:37.308+0000] {processor.py:154} INFO - Started process (PID=2147) to work on /opt/airflow/dags/6.2-monitoring.py
[2022-11-08T20:55:37.309+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/6.2-monitoring.py for tasks to queue
[2022-11-08T20:55:37.311+0000] {logging_mixin.py:120} INFO - [2022-11-08T20:55:37.310+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/6.2-monitoring.py
[2022-11-08T20:55:37.362+0000] {processor.py:766} INFO - DAG(s) dict_keys(['6-monitoring_2']) retrieved from /opt/airflow/dags/6.2-monitoring.py
[2022-11-08T20:55:38.359+0000] {logging_mixin.py:120} INFO - [2022-11-08T20:55:38.359+0000] {manager.py:507} INFO - Created Permission View: can read on DAG:6-monitoring_2
[2022-11-08T20:55:38.374+0000] {logging_mixin.py:120} INFO - [2022-11-08T20:55:38.373+0000] {manager.py:507} INFO - Created Permission View: can edit on DAG:6-monitoring_2
[2022-11-08T20:55:38.390+0000] {logging_mixin.py:120} INFO - [2022-11-08T20:55:38.389+0000] {manager.py:507} INFO - Created Permission View: can delete on DAG:6-monitoring_2
[2022-11-08T20:55:38.390+0000] {logging_mixin.py:120} INFO - [2022-11-08T20:55:38.390+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-08T20:55:38.413+0000] {logging_mixin.py:120} INFO - [2022-11-08T20:55:38.413+0000] {dag.py:2606} INFO - Creating ORM DAG for 6-monitoring_2
[2022-11-08T20:55:38.425+0000] {logging_mixin.py:120} INFO - [2022-11-08T20:55:38.425+0000] {dag.py:3340} INFO - Setting next_dagrun for 6-monitoring_2 to 2022-01-01T00:00:00+00:00, run_after=2022-01-02T00:00:00+00:00
[2022-11-08T20:55:38.461+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/6.2-monitoring.py took 1.158 seconds
[2022-11-08T20:56:08.827+0000] {processor.py:154} INFO - Started process (PID=2181) to work on /opt/airflow/dags/6.2-monitoring.py
[2022-11-08T20:56:08.829+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/6.2-monitoring.py for tasks to queue
[2022-11-08T20:56:08.832+0000] {logging_mixin.py:120} INFO - [2022-11-08T20:56:08.832+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/6.2-monitoring.py
[2022-11-08T20:56:08.879+0000] {processor.py:766} INFO - DAG(s) dict_keys(['6-monitoring_2']) retrieved from /opt/airflow/dags/6.2-monitoring.py
[2022-11-08T20:56:08.916+0000] {logging_mixin.py:120} INFO - [2022-11-08T20:56:08.916+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-08T20:56:08.980+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/6.2-monitoring.py took 0.159 seconds
[2022-11-08T20:56:39.127+0000] {processor.py:154} INFO - Started process (PID=2219) to work on /opt/airflow/dags/6.2-monitoring.py
[2022-11-08T20:56:39.128+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/6.2-monitoring.py for tasks to queue
[2022-11-08T20:56:39.129+0000] {logging_mixin.py:120} INFO - [2022-11-08T20:56:39.129+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/6.2-monitoring.py
[2022-11-08T20:56:39.150+0000] {processor.py:766} INFO - DAG(s) dict_keys(['6-monitoring_2']) retrieved from /opt/airflow/dags/6.2-monitoring.py
[2022-11-08T20:56:39.180+0000] {logging_mixin.py:120} INFO - [2022-11-08T20:56:39.180+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-08T20:56:39.227+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/6.2-monitoring.py took 0.104 seconds
[2022-11-08T20:57:09.639+0000] {processor.py:154} INFO - Started process (PID=2248) to work on /opt/airflow/dags/6.2-monitoring.py
[2022-11-08T20:57:09.640+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/6.2-monitoring.py for tasks to queue
[2022-11-08T20:57:09.641+0000] {logging_mixin.py:120} INFO - [2022-11-08T20:57:09.641+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/6.2-monitoring.py
[2022-11-08T20:57:09.661+0000] {processor.py:766} INFO - DAG(s) dict_keys(['6-monitoring_2']) retrieved from /opt/airflow/dags/6.2-monitoring.py
[2022-11-08T20:57:09.686+0000] {logging_mixin.py:120} INFO - [2022-11-08T20:57:09.686+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-08T20:57:09.731+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/6.2-monitoring.py took 0.095 seconds
[2022-11-08T20:57:40.258+0000] {processor.py:154} INFO - Started process (PID=2286) to work on /opt/airflow/dags/6.2-monitoring.py
[2022-11-08T20:57:40.259+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/6.2-monitoring.py for tasks to queue
[2022-11-08T20:57:40.260+0000] {logging_mixin.py:120} INFO - [2022-11-08T20:57:40.260+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/6.2-monitoring.py
[2022-11-08T20:57:40.281+0000] {processor.py:766} INFO - DAG(s) dict_keys(['6-monitoring_2']) retrieved from /opt/airflow/dags/6.2-monitoring.py
[2022-11-08T20:57:40.310+0000] {logging_mixin.py:120} INFO - [2022-11-08T20:57:40.310+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-08T20:57:40.361+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/6.2-monitoring.py took 0.105 seconds
[2022-11-08T20:58:10.941+0000] {processor.py:154} INFO - Started process (PID=2314) to work on /opt/airflow/dags/6.2-monitoring.py
[2022-11-08T20:58:10.942+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/6.2-monitoring.py for tasks to queue
[2022-11-08T20:58:10.943+0000] {logging_mixin.py:120} INFO - [2022-11-08T20:58:10.942+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/6.2-monitoring.py
[2022-11-08T20:58:10.963+0000] {processor.py:766} INFO - DAG(s) dict_keys(['6-monitoring_2']) retrieved from /opt/airflow/dags/6.2-monitoring.py
[2022-11-08T20:58:10.993+0000] {logging_mixin.py:120} INFO - [2022-11-08T20:58:10.993+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-08T20:58:11.039+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/6.2-monitoring.py took 0.102 seconds
[2022-11-08T20:58:41.904+0000] {processor.py:154} INFO - Started process (PID=2351) to work on /opt/airflow/dags/6.2-monitoring.py
[2022-11-08T20:58:41.905+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/6.2-monitoring.py for tasks to queue
[2022-11-08T20:58:41.906+0000] {logging_mixin.py:120} INFO - [2022-11-08T20:58:41.906+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/6.2-monitoring.py
[2022-11-08T20:58:41.929+0000] {processor.py:766} INFO - DAG(s) dict_keys(['6-monitoring_2']) retrieved from /opt/airflow/dags/6.2-monitoring.py
[2022-11-08T20:58:41.956+0000] {logging_mixin.py:120} INFO - [2022-11-08T20:58:41.956+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-08T20:58:42.004+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/6.2-monitoring.py took 0.103 seconds
[2022-11-08T20:59:12.421+0000] {processor.py:154} INFO - Started process (PID=2379) to work on /opt/airflow/dags/6.2-monitoring.py
[2022-11-08T20:59:12.422+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/6.2-monitoring.py for tasks to queue
[2022-11-08T20:59:12.424+0000] {logging_mixin.py:120} INFO - [2022-11-08T20:59:12.423+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/6.2-monitoring.py
[2022-11-08T20:59:12.447+0000] {processor.py:766} INFO - DAG(s) dict_keys(['6-monitoring_2']) retrieved from /opt/airflow/dags/6.2-monitoring.py
[2022-11-08T20:59:12.474+0000] {logging_mixin.py:120} INFO - [2022-11-08T20:59:12.474+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-08T20:59:12.523+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/6.2-monitoring.py took 0.106 seconds
[2022-11-08T23:59:29.276+0000] {processor.py:154} INFO - Started process (PID=2398) to work on /opt/airflow/dags/6.2-monitoring.py
[2022-11-08T23:59:29.300+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/6.2-monitoring.py for tasks to queue
[2022-11-08T23:59:29.307+0000] {logging_mixin.py:120} INFO - [2022-11-08T23:59:29.307+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/6.2-monitoring.py
[2022-11-08T23:59:31.776+0000] {processor.py:766} INFO - DAG(s) dict_keys(['6-monitoring_2']) retrieved from /opt/airflow/dags/6.2-monitoring.py
[2022-11-08T23:59:36.066+0000] {logging_mixin.py:120} INFO - [2022-11-08T23:59:36.066+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-08T23:59:36.149+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/6.2-monitoring.py took 6.993 seconds
