[2022-11-15T16:55:32.741+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: 8-templating.task1 scheduled__2022-07-01T00:00:00+00:00 [queued]>
[2022-11-15T16:55:32.761+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: 8-templating.task1 scheduled__2022-07-01T00:00:00+00:00 [queued]>
[2022-11-15T16:55:32.762+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-15T16:55:32.763+0000] {taskinstance.py:1363} INFO - Starting attempt 2 of 2
[2022-11-15T16:55:32.764+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-15T16:55:32.784+0000] {taskinstance.py:1383} INFO - Executing <Task(BashOperator): task1> on 2022-07-01 00:00:00+00:00
[2022-11-15T16:55:32.791+0000] {standard_task_runner.py:55} INFO - Started process 1472 to run task
[2022-11-15T16:55:32.803+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', '8-templating', 'task1', 'scheduled__2022-07-01T00:00:00+00:00', '--job-id', '1065', '--raw', '--subdir', 'DAGS_FOLDER/8-templating.py', '--cfg-path', '/tmp/tmphacdmj2z']
[2022-11-15T16:55:32.804+0000] {standard_task_runner.py:83} INFO - Job 1065: Subtask task1
[2022-11-15T16:55:32.885+0000] {task_command.py:376} INFO - Running <TaskInstance: 8-templating.task1 scheduled__2022-07-01T00:00:00+00:00 [running]> on host 638485efabe7
[2022-11-15T16:55:32.935+0000] {abstractoperator.py:421} ERROR - Exception rendering Jinja template for task 'task1', field 'bash_command'. Template: '"\n{% for file in filenames %}\n    echo "{{ ds }}"\n    echo "{{ file }}"\n{% endfor %}\n'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 414, in _do_render_template_fields
    seen_oids,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 474, in render_template
    return render_template_to_string(template, context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/helpers.py", line 288, in render_template_to_string
    return render_template(template, cast(MutableMapping[str, Any], context), native=False)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/helpers.py", line 283, in render_template
    return "".join(nodes)
  File "<template>", line 13, in root
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/runtime.py", line 852, in _fail_with_undefined_error
    raise self._undefined_exception(self._undefined_message)
jinja2.exceptions.UndefinedError: 'filenames' is undefined
[2022-11-15T16:55:32.940+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1457, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1576, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2199, in render_templates
    original_task.render_template_fields(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 1193, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 75, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 414, in _do_render_template_fields
    seen_oids,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 474, in render_template
    return render_template_to_string(template, context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/helpers.py", line 288, in render_template_to_string
    return render_template(template, cast(MutableMapping[str, Any], context), native=False)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/helpers.py", line 283, in render_template
    return "".join(nodes)
  File "<template>", line 13, in root
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/runtime.py", line 852, in _fail_with_undefined_error
    raise self._undefined_exception(self._undefined_message)
jinja2.exceptions.UndefinedError: 'filenames' is undefined
[2022-11-15T16:55:32.951+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=8-templating, task_id=task1, execution_date=20220701T000000, start_date=20221115T165532, end_date=20221115T165532
[2022-11-15T16:55:32.970+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 1065 for task task1 ('filenames' is undefined; 1472)
[2022-11-15T16:55:33.010+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-11-15T16:55:33.032+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
