[2022-11-04T18:58:55.804+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: orquestacion.TASK1 scheduled__2022-05-01T00:00:00+00:00 [queued]>
[2022-11-04T18:58:55.845+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: orquestacion.TASK1 scheduled__2022-05-01T00:00:00+00:00 [queued]>
[2022-11-04T18:58:55.847+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-04T18:58:55.848+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-11-04T18:58:55.851+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-04T18:58:55.893+0000] {taskinstance.py:1383} INFO - Executing <Task(BashOperator): TASK1> on 2022-05-01 00:00:00+00:00
[2022-11-04T18:58:55.929+0000] {standard_task_runner.py:55} INFO - Started process 4675 to run task
[2022-11-04T18:58:55.936+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'orquestacion', 'TASK1', 'scheduled__2022-05-01T00:00:00+00:00', '--job-id', '28', '--raw', '--subdir', 'DAGS_FOLDER/5.1-orquestacion.py', '--cfg-path', '/tmp/tmprae4a9ys']
[2022-11-04T18:58:55.939+0000] {standard_task_runner.py:83} INFO - Job 28: Subtask TASK1
[2022-11-04T18:58:56.107+0000] {task_command.py:376} INFO - Running <TaskInstance: orquestacion.TASK1 scheduled__2022-05-01T00:00:00+00:00 [running]> on host c7d12af55512
[2022-11-04T18:58:56.417+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=orquestacion
AIRFLOW_CTX_TASK_ID=TASK1
AIRFLOW_CTX_EXECUTION_DATE=2022-05-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-05-01T00:00:00+00:00
[2022-11-04T18:58:56.491+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2022-11-04T18:58:56.493+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', "SLEEP 2 && ECHO 'TASK1'"]
[2022-11-04T18:58:56.588+0000] {subprocess.py:86} INFO - Output:
[2022-11-04T18:58:56.714+0000] {subprocess.py:93} INFO - /bin/bash: line 1: SLEEP: command not found
[2022-11-04T18:58:56.717+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2022-11-04T18:58:56.743+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2022-11-04T18:58:56.758+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=orquestacion, task_id=TASK1, execution_date=20220501T000000, start_date=20221104T185855, end_date=20221104T185856
[2022-11-04T18:58:56.794+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 28 for task TASK1 (Bash command failed. The command returned a non-zero exit code 127.; 4675)
[2022-11-04T18:58:56.837+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-11-04T18:58:56.906+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
